---
title: "False_Bay_monitoring_tides"
author: "Wendel Raymond"
date: "April 5, 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
## False Bay Monitoring Tides
Extract and view tides critical for the water quality monitoring project. 

```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(rtide)
library(scales)
```


### Get tide data
From April to September 2021
```{r}
## Data extract ##
dat <- rtide::tide_height("Port Townsend", from = as.Date("2021-04-01"), to = as.Date("2021-04-30"), minutes = 10L, tz = "PST8PDT")

## add feet column ##
dat$TideHeight_ft <- dat$TideHeight * 3.281

## Clean up date data ##
dat$DateTime <- as.POSIXct(dat$DateTime, format = "%Y-%m-%d %h:%m:%s", tz = "PST8PDT")

dat <- dat %>% 
  separate(DateTime, c("date", "time"), sep = " ", remove = FALSE)
```

Quick plot
```{r}
ggplot(dat) +
  geom_line(aes(x = DateTime, y = TideHeight_ft)) +
  scale_x_datetime(labels = date_format("%d")) +
  geom_hline(aes(yintercept = 4), color = "red")
```

### Filter tide data

Filter for all data when height is <= 4 feet. 
```{r}
dat.redu <- dat %>%
  filter(TideHeight_ft <= 4)

unique(dat.redu$date)
```

